#!/data/data/com.termux/files/usr/bin/bash
#
# Claw Notes - Setup Script
#
# Sets up OpenClaw as your always-on AI assistant.
#
# Architecture:
#   CODE  → This repo (scripts, widgets) - stays in git
#   DATA  → Vault (notes, journals) - synced to cloud separately

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

step() { echo -e "${CYAN}[$1/$2]${NC} $3"; }
ok() { echo -e "${GREEN}  ✓${NC} $1"; }
warn() { echo -e "${YELLOW}  !${NC} $1"; }

echo ""
echo -e "${CYAN}╔══════════════════════════════════════╗${NC}"
echo -e "${CYAN}║       Claw Notes Setup               ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════╝${NC}"
echo ""

# Detect environment
if [ -d "/data/data/com.termux" ]; then
    ENV="termux"
else
    ENV="linux"
    warn "Not running in Termux. Some features won't work."
    echo ""
fi

TOTAL=9

# Step 1: Update packages
step 1 $TOTAL "Updating packages..."
if [ "$ENV" = "termux" ]; then
    pkg update -y > /dev/null 2>&1 && pkg upgrade -y > /dev/null 2>&1
    ok "Packages updated"
else
    ok "Skipped"
fi

# Step 2: Install core dependencies
step 2 $TOTAL "Installing Node.js, Git, Termux:API..."
if [ "$ENV" = "termux" ]; then
    pkg install -y nodejs-lts git termux-api jq curl > /dev/null 2>&1
    ok "Core dependencies installed"
else
    ok "Ensure nodejs, git, jq, curl are installed"
fi

# Step 3: Install OpenClaw
step 3 $TOTAL "Installing OpenClaw..."
if npm install -g openclaw > /dev/null 2>&1; then
    ok "OpenClaw installed"
else
    warn "OpenClaw install failed - try: npm install -g openclaw"
fi

# Step 4: Setup storage
step 4 $TOTAL "Setting up storage access..."
if [ "$ENV" = "termux" ]; then
    if [ ! -d "$HOME/storage" ]; then
        echo "    Grant storage permission when prompted..."
        termux-setup-storage
        sleep 2
    fi
    ok "Storage access ready"
else
    ok "Skipped"
fi

# Step 5: Configure vault location (DATA separate from CODE)
step 5 $TOTAL "Configuring vault location..."
echo ""
echo "    Your notes/data will be stored separately from code."
echo "    This allows cloud sync without exposing the code repo."
echo ""

# Default vault locations
if [ "$ENV" = "termux" ]; then
    DEFAULT_VAULT="$HOME/storage/shared/Documents/ClawNotes-Vault"
else
    DEFAULT_VAULT="$HOME/ClawNotes-Vault"
fi

echo "    Default: $DEFAULT_VAULT"
read -p "    Press Enter to accept, or type custom path: " CUSTOM_VAULT

VAULT_ROOT="${CUSTOM_VAULT:-$DEFAULT_VAULT}"

# Create vault directories
mkdir -p "$VAULT_ROOT/pages" \
         "$VAULT_ROOT/journals" \
         "$VAULT_ROOT/transcripts/raw" \
         "$VAULT_ROOT/transcripts/cleaned" \
         "$VAULT_ROOT/summaries" \
         "$VAULT_ROOT/assets" \
         "$VAULT_ROOT/templates"

# Copy templates to vault if not exists
if [ ! -f "$VAULT_ROOT/templates/note.md" ] && [ -d "$SCRIPT_DIR/templates" ]; then
    cp -r "$SCRIPT_DIR/templates/"* "$VAULT_ROOT/templates/" 2>/dev/null || true
fi

# Copy Syncthing ignore file to vault root (for cloud sync)
if [ ! -f "$VAULT_ROOT/.stignore" ] && [ -f "$SCRIPT_DIR/templates/.stignore" ]; then
    cp "$SCRIPT_DIR/templates/.stignore" "$VAULT_ROOT/.stignore" 2>/dev/null || true
fi

# Optionally seed vault with example content
if [ -d "$SCRIPT_DIR/pages" ] && [ ! -f "$VAULT_ROOT/pages/welcome.md" ]; then
    echo ""
    read -p "    Copy example notes to vault? [Y/n] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        cp -r "$SCRIPT_DIR/pages/"* "$VAULT_ROOT/pages/" 2>/dev/null || true
        cp -r "$SCRIPT_DIR/journals/"* "$VAULT_ROOT/journals/" 2>/dev/null || true
        ok "Example content copied to vault"
    fi
fi

# Save user config
mkdir -p "$HOME/.config/claw-notes"
cat > "$HOME/.config/claw-notes/config" <<EOF
# Claw Notes User Configuration
# Generated by setup.sh

# Code location (this repo)
CLAW_ROOT="$SCRIPT_DIR"

# Vault location (your notes - sync this to cloud)
VAULT_ROOT="$VAULT_ROOT"
EOF

ok "Vault created at: $VAULT_ROOT"

# Step 6: Configure API keys for transcription
step 6 $TOTAL "Configuring API keys..."
echo ""
echo "    OpenClaw uses cloud APIs for voice transcription."
echo "    You need at least one API key (OpenAI recommended)."
echo ""

OPENCLAW_DIR="$HOME/.openclaw"
OPENCLAW_CONFIG="$OPENCLAW_DIR/openclaw.json"
mkdir -p "$OPENCLAW_DIR"

CONFIGURE_KEYS=true
if [ -f "$OPENCLAW_CONFIG" ]; then
    echo "    Found existing config at $OPENCLAW_CONFIG"
    read -p "    Update API keys? [y/N] " -n 1 -r
    echo ""
    [[ ! $REPLY =~ ^[Yy]$ ]] && CONFIGURE_KEYS=false
fi

if [ "$CONFIGURE_KEYS" = true ]; then
    echo ""
    read -sp "    OpenAI API key: " OPENAI_KEY
    echo ""
    read -sp "    OpenRouter API key (optional): " OPENROUTER_KEY
    echo ""
    echo ""

    if [ -z "$OPENAI_KEY" ] && [ -z "$OPENROUTER_KEY" ]; then
        warn "No API keys provided - transcription won't work"
    fi

    if [ -n "$OPENAI_KEY" ]; then
        AUDIO_PROVIDER="openai"
        AUDIO_MODEL="whisper-1"
    elif [ -n "$OPENROUTER_KEY" ]; then
        AUDIO_PROVIDER="openrouter"
        AUDIO_MODEL="openai/whisper-large-v3"
    else
        AUDIO_PROVIDER="openai"
        AUDIO_MODEL="whisper-1"
    fi

    # Build config - workspace points to VAULT, not code repo
    CONFIG=$(jq -n \
        --arg workspace "$VAULT_ROOT" \
        --arg openai_key "$OPENAI_KEY" \
        --arg openrouter_key "$OPENROUTER_KEY" \
        --arg audio_provider "$AUDIO_PROVIDER" \
        --arg audio_model "$AUDIO_MODEL" \
        '{
            gateway: { host: "127.0.0.1", port: 3000 },
            workspace: { root: $workspace },
            providers: (
                {}
                | if $openai_key != "" then . + { openai: { apiKey: $openai_key } } else . end
                | if $openrouter_key != "" then . + { openrouter: { apiKey: $openrouter_key } } else . end
            ),
            tools: {
                media: {
                    audio: {
                        enabled: true,
                        models: [{ provider: $audio_provider, model: $audio_model }]
                    }
                }
            },
            channels: { whatsapp: { enabled: true } }
        }')

    echo "$CONFIG" > "$OPENCLAW_CONFIG"
    ok "Config saved"
else
    ok "Keeping existing config"
fi

# Step 7: Setup widgets (symlinks to home)
step 7 $TOTAL "Setting up home screen widgets..."
chmod +x "$SCRIPT_DIR/.shortcuts/"* 2>/dev/null || true
chmod +x "$SCRIPT_DIR/.shortcuts/tasks/"* 2>/dev/null || true
chmod +x "$SCRIPT_DIR/.claw/bin/"* 2>/dev/null || true
chmod +x "$SCRIPT_DIR/.claw/boot/"* 2>/dev/null || true

if [ "$ENV" = "termux" ]; then
    mkdir -p "$HOME/.shortcuts/tasks"

    for widget in "$SCRIPT_DIR/.shortcuts/"*; do
        [ -d "$widget" ] && continue
        name=$(basename "$widget")
        ln -sf "$widget" "$HOME/.shortcuts/$name" 2>/dev/null || true
    done

    for task in "$SCRIPT_DIR/.shortcuts/tasks/"*; do
        name=$(basename "$task")
        ln -sf "$task" "$HOME/.shortcuts/tasks/$name" 2>/dev/null || true
    done

    ok "Widgets linked to ~/.shortcuts/"
else
    ok "Scripts ready"
fi

# Step 8: Setup boot auto-start
step 8 $TOTAL "Setting up auto-start on boot..."
if [ "$ENV" = "termux" ]; then
    # Create ~/.termux/boot/ if it doesn't exist
    mkdir -p "$HOME/.termux/boot"

    # Copy boot script (not symlink - needs to work even if repo moves)
    cp "$SCRIPT_DIR/.claw/boot/start-claw.sh" "$HOME/.termux/boot/start-claw.sh"
    chmod +x "$HOME/.termux/boot/start-claw.sh"

    # Update boot script with actual paths
    sed -i "s|CLAW_ROOT=\"\"|CLAW_ROOT=\"$SCRIPT_DIR\"|g" "$HOME/.termux/boot/start-claw.sh" 2>/dev/null || true

    ok "Boot script installed to ~/.termux/boot/"
    echo "    Note: Install Termux:Boot from F-Droid for auto-start"
else
    ok "Skipped (Termux only)"
fi

# Step 9: Start assistant
step 9 $TOTAL "Starting assistant..."
if command -v openclaw &> /dev/null && [ "$ENV" = "termux" ]; then
    "$SCRIPT_DIR/.claw/boot/watchdog.sh" --daemon 2>/dev/null
    sleep 2
    if pgrep -f "openclaw" > /dev/null 2>&1; then
        ok "Assistant running"
    else
        warn "Start manually: openclaw gateway"
    fi
else
    warn "Start later with: openclaw gateway"
fi

echo ""
echo -e "${GREEN}╔══════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       Setup Complete!                ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════╝${NC}"
echo ""

echo "Configuration:"
echo "  Code:  $SCRIPT_DIR"
echo "  Vault: $VAULT_ROOT"
echo ""

if [ "$ENV" = "termux" ]; then
    echo "How to use:"
    echo ""
    echo "  1. Add Termux:Widget to your home screen"
    echo ""
    echo "  2. Tap 'Record Voice' → transcribes via OpenAI"
    echo ""
    echo "  3. Or send voice notes to WhatsApp assistant"
    echo ""
    echo "  4. Your notes are in: $VAULT_ROOT"
    echo ""
    echo "Cloud sync (optional):"
    echo "  Sync your vault folder with any app:"
    echo "  - Syncthing (recommended, F-Droid)"
    echo "  - FolderSync, Dropsync"
    echo "  - Google Drive, Dropbox app"
    echo ""

    if command -v termux-notification &> /dev/null; then
        termux-notification \
            --title "Claw Notes Ready" \
            --content "Vault: $VAULT_ROOT"
    fi
else
    echo "Usage:"
    echo "  openclaw gateway   # Start the assistant"
    echo "  openclaw onboard   # Connect WhatsApp"
    echo ""
    echo "Sync vault with Syncthing or any folder sync tool"
    echo ""
fi
